// Automatically generated by declarative-routing, do NOT edit
import { z } from "zod";
import { makeDeleteRoute, makeGetRoute, makePostRoute, makeRoute } from "./makeRoute";

const defaultInfo = {
  search: z.object({})
};

import * as HomeRoute from "@/app/page.info";
import * as ApiapplicationRoute from "@/app/api/application/route.info";
import * as ApiCategoryRoute from "@/app/api/category/route.info";
import * as ApiProductsRoute from "@/app/api/products/route.info";
import * as ApiStackRoute from "@/app/api/stack/route.info";
import * as DashboardRoute from "@/app/dashboard/page.info";
import * as DashboardLanguageRoute from "@/app/dashboard/language/page.info";
import * as DashboardProjectsRoute from "@/app/dashboard/projects/page.info";
import * as DashboardProjectsAddnewRoute from "@/app/dashboard/projects/add-new/page.info";
import * as DashboardprojectseditidRoute from "@/app/dashboard/projects/edit/[id]/page.info";
import * as DashboardStacksRoute from "@/app/dashboard/stacks/page.info";
import * as ProjectsRoute from "@/app/projects/page.info";
import * as ProjectsidRoute from "@/app/projects/[id]/page.info";

export const Home = makeRoute(
  "/",
  {
    ...defaultInfo,
    ...HomeRoute.Route
  }
);
export const Dashboard = makeRoute(
  "/dashboard",
  {
    ...defaultInfo,
    ...DashboardRoute.Route
  }
);
export const DashboardLanguage = makeRoute(
  "/dashboard/language",
  {
    ...defaultInfo,
    ...DashboardLanguageRoute.Route
  }
);
export const DashboardProjects = makeRoute(
  "/dashboard/projects",
  {
    ...defaultInfo,
    ...DashboardProjectsRoute.Route
  }
);
export const DashboardProjectsAddnew = makeRoute(
  "/dashboard/projects/add-new",
  {
    ...defaultInfo,
    ...DashboardProjectsAddnewRoute.Route
  }
);
export const Dashboardprojectseditid = makeRoute(
  "/dashboard/projects/edit/[id]",
  {
    ...defaultInfo,
    ...DashboardprojectseditidRoute.Route
  }
);
export const DashboardStacks = makeRoute(
  "/dashboard/stacks",
  {
    ...defaultInfo,
    ...DashboardStacksRoute.Route
  }
);
export const Projects = makeRoute(
  "/projects",
  {
    ...defaultInfo,
    ...ProjectsRoute.Route
  }
);
export const Projectsid = makeRoute(
  "/projects/[id]",
  {
    ...defaultInfo,
    ...ProjectsidRoute.Route
  }
);

export const getApiapplication = makeGetRoute(
  "/api/application",
  {
    ...defaultInfo,
    ...ApiapplicationRoute.Route
  },
  ApiapplicationRoute.GET
);
export const getApiCategory = makeGetRoute(
  "/api/category",
  {
    ...defaultInfo,
    ...ApiCategoryRoute.Route
  },
  ApiCategoryRoute.GET
);
export const getApiProducts = makeGetRoute(
  "/api/products",
  {
    ...defaultInfo,
    ...ApiProductsRoute.Route
  },
  ApiProductsRoute.GET
);
export const postApiProducts = makePostRoute(
  "/api/products",
  {
    ...defaultInfo,
    ...ApiProductsRoute.Route
  },
  ApiProductsRoute.POST
);
export const deleteApiProducts = makeDeleteRoute(
  "/api/products",
  {
    ...defaultInfo,
    ...ApiProductsRoute.Route
  },
  
);
export const getApiStack = makeGetRoute(
  "/api/stack",
  {
    ...defaultInfo,
    ...ApiStackRoute.Route
  },
  ApiStackRoute.GET
);
