// Automatically generated by declarative-routing, do NOT edit
import { z } from "zod";
import { makeRoute } from "./makeRoute";

const defaultInfo = {
  search: z.object({})
};

import * as HomeRoute from "@/app/page.info";
import * as BlogRoute from "@/app/blog/page.info";
import * as DashboardRoute from "@/app/dashboard/page.info";
import * as DashboardProjectsRoute from "@/app/dashboard/projects/page.info";
import * as ProjectsRoute from "@/app/projects/page.info";

export const Home = makeRoute(
  "/",
  {
    ...defaultInfo,
    ...HomeRoute.Route
  }
);
export const Blog = makeRoute(
  "/blog",
  {
    ...defaultInfo,
    ...BlogRoute.Route
  }
);
export const Dashboard = makeRoute(
  "/dashboard",
  {
    ...defaultInfo,
    ...DashboardRoute.Route
  }
);
export const DashboardProjects = makeRoute(
  "/dashboard/projects",
  {
    ...defaultInfo,
    ...DashboardProjectsRoute.Route
  }
);
export const Projects = makeRoute(
  "/projects",
  {
    ...defaultInfo,
    ...ProjectsRoute.Route
  }
);

