import type { Metadata } from "next";
import { Inter } from "next/font/google";
import SideNav from "../_components/ui/sideNav";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function DashboardLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body  className={`bg-black text-white flex ${inter.className}`}>
      <div className="flex-1">
        <SideNav />
        </div>
        <main className="flex-[6] p-8">
          {children}
        </main>
      </body>
    </html>
  );
}
