import type { Metadata } from "next";
import { Inter } from "next/font/google";
import SideNav from "../_components/ui/sideNav";
import { Toaster } from "@/components/ui/toaster";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function DashboardLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <div className={` text-white flex ${inter.className}`}>
        <div className="flex-1">
          <SideNav />
        </div>
        <main className="flex-[6] px-8">
          {children}
        <Toaster />
        </main>
      </div>
  );
}
