export default [
  {
    id: 1,
    author: "Oyekanmi",
    image: "https://i.ibb.co/G9cnmDD/Screenshot-19.png",
    name: "navbar js",
    language: ["html", "css", "javascript"],
    category: "javascript",
    url: "https://oyekanm.github.io/Navigation-js/",
    Github: "https://github.com/oyekanm/Navigation-js",
  },
  {
    id: 5,
    author: "Oyekanmi",
    image: "https://i.ibb.co/5GVD76B/Screenshot-11.png",
    name: "natours",
    language: ["html", "css", "sass"],
    category: "sass",
    url: "https://oyekanm.github.io/NATOURS/",
    Github: "https://github.com/oyekanm/NATOURS",
  },
  {
    id: 6,
    author: "Oyekanmi",
    image: "https://i.ibb.co/30QNFyP/Screenshot-13.png",
    name: "trillo",
    language: ["html", "css", "sass"],
    category: "sass",
    url: "https://oyekanm.github.io/TRILLO/",
    Github: "https://github.com/oyekanm/TRILLO",
  },
  {
    id: 7,
    author: "Oyekanmi",
    image: "https://i.ibb.co/YfQPvjr/Screenshot-12.png",
    name: "nexter",
    language: ["html", "css", "sass"],
    category: "sass",
    url: "https://nextergrid.netlify.app/",
    Github: "https://github.com/oyekanm/NEXTER",
  },
  {
    id: 11,
    author: "Oyekanmi",
    image: "https://i.ibb.co/mNp7gxS/Screenshot-24.png",
    name: "trivial questions",
    language: ["react", "css"],
    category: "react",
    url: "http://trivial-questions-iywp.vercel.app/",
    Github: "https://github.com/oyekanm/Trivial-Questions",
  }, 
  {
    id: 12,
    author: "Oyekanmi",
    image: "https://i.ibb.co/KNXHyt7/Screenshot-32.png",
    name: "gsap animation",
    language: ["html", "css", "gsap"],
    category: "javascript",
    url: "https://gsap-testing.netlify.app/",
    Github: "https://github.com/oyekanm/Gsap",
  },
  {
    id: 13,
    author: "Oyekanmi",
    image: "https://i.ibb.co/myTQb90/Screenshot-30.png",
    name: "cart",
    language: ["react", "css", "redux"],
    category: "react",
    url: "http://cart-navy.vercel.app/",
    Github: "https://github.com/oyekanm/cart",
  },
  {
    id: 14,
    author: "Oyekanmi",
    image: "https://i.ibb.co/gjvMGhH/Screenshot-27.png",
    name: "fake review comment ",
    language: ["nextjs", "css"],
    category: "nextjs",
    url: "http://my-app-oyekanm.vercel.app/",
    Github: "https://github.com/oyekanm/my-app",
  },
  {
    id: 15,
    author: "Oyekanmi",
    image: "https://i.ibb.co/74s3zRG/Screenshot-28.png",
    name: "pagination",
    language: ["react", "bootstrap", "react query"],
    category: "react",
    url: "http://pagination-teal.vercel.app/",
    Github: "https://github.com/oyekanm/Pagination",
  },
  {
    id: 17,
    author: "Oyekanmi",
    image: "https://i.ibb.co/dDx7PCr/Screenshot-25.png",
    name: "news search",
    language: ["react", "css", "bootstrap"],
    category: "react",
    url: "http://search-news-delta.vercel.app/",
    Github: "https://github.com/oyekanm/Search-News",
  },
  {
    id: 18,
    author: "Oyekanmi",
    image: "https://i.ibb.co/dfNfn1L/Screenshot-29.png",
    name: "food menu",
    language: ["react", "css"],
    category: "react",
    url: "http://menu-oyekanm.vercel.app/",
    Github: "https://github.com/oyekanm/menu",
  },
  {
    id: 19,
    author: "Oyekanmi",
    image: "https://i.ibb.co/nB8ty16/Screenshot-34.png",
    name: "homesmart",
    language: ["react", "css", "bootstrap"],
    category: "react",
    url: "https://homesmart-rental.netlify.app/",
    Github: "https://github.com/oyekanm/Homesmart-React",
  },
  {
    id: 20,
    author: "Oyekanmi",
    image: "https://i.ibb.co/fknLJQ4/Screenshot-26.png",
    name: "cocktails ",
    language: ["react", "css"],
    category: "react",
    url: "http://cocktail-search.vercel.app/",
    Github: "https://github.com/oyekanm/Cocktail-Search",
  },
  {
    id: 21,
    author: "Oyekanmi",
    image: "https://i.ibb.co/CVKRSzj/Screenshot-39.png",
    name: "crappo landing page",
    language: ["html", "sass", "aos", "gsap"],
    category: "sass",
    url: "http://crypto-home-page-zeta.vercel.app/",
    Github: "https://github.com/oyekanm/Crypto-Landing-Page",
  },
  {
    id: 22,
    author: "Oyekanmi",
    image: "https://i.ibb.co/3dJ90f7/Screenshot-38.png",
    name: "portfolio",
    language: ["react", "css", "aos", "framer-motion"],
    category: "react",
    url: "https://github.com/oyekanm/Project-House",
    Github: "https://github.com/oyekanm/Project-House",
  },
  {
    id: 23,
    author: "Oyekanmi",
    image: "https://i.ibb.co/5kYcksd/Screenshot-33.png",
    name: "eko360 react",
    language: ["react", "css", "bootstrap"],
    category: "react",
    url: "http://eko360-react.vercel.app/",
    Github: "https://github.com/oyekanm/Eko360-React",
  },
  {
    id: 24,
    author: "Oyekanmi",
    image: "https://i.ibb.co/LYSmvYF/Screenshot-31.png",
    name: "tenzies",
    language: ["react", "css"],
    category: "react",
    url: "http://tenzies-seven.vercel.app/",
    Github: "https://github.com/oyekanm/Tenzies",
  },
];
